### ISSUE TITLE
项目非常棒，想请教下您......

### ISSUE THREAD

**Issue by wfsqwangdoudou** [yzxliu/VAG.Node#1]
我下载了您的源码，预览我已经搭好了，但需求远远不够，希望在这个基础上开发公司视频平台，
方便留下联系方式吗？想和您进一步沟通，十分希望和您合作（想聘用您作为兼职/全职开发，或者开发技术顾问，具体看您的时间），我的微信+电话17802117871。

**Comment by crazybber** [comment]
欢迎来群里交流：https://github.com/GB28181/GB28181.Solution/blob/develop/README.md
